// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ6QNlD1NPdqlI2wRogWNBWsVqWXF8a3o',
    appId: '1:465540361646:web:944a070bdcf5ddd7e6ac3f',
    messagingSenderId: '465540361646',
    projectId: 'instagram-flutter-360b8',
    authDomain: 'instagram-flutter-360b8.firebaseapp.com',
    storageBucket: 'instagram-flutter-360b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA20x45byQ-luGVgRApF4n5Lg0PBX0-lo',
    appId: '1:465540361646:android:0ef8046519ad4620e6ac3f',
    messagingSenderId: '465540361646',
    projectId: 'instagram-flutter-360b8',
    storageBucket: 'instagram-flutter-360b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJA7sKwf1OCBr3Wg8Ho-u2t39jdVRY37c',
    appId: '1:465540361646:ios:626bf8fcdee9e726e6ac3f',
    messagingSenderId: '465540361646',
    projectId: 'instagram-flutter-360b8',
    storageBucket: 'instagram-flutter-360b8.appspot.com',
    iosClientId: '465540361646-7dgal7215g0sr8ea57lc0t6tmib12k71.apps.googleusercontent.com',
    iosBundleId: 'com.sqisoft.instagramflutter',
  );
}
